# Generated by Django 2.1.7 on 2019-03-09 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('states', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='created_from',
            field=models.CharField(blank=True, default='N/A', max_length=200, null=True),
        ),
    ]
