# Generated by Django 2.1.7 on 2019-03-09 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('states', '0002_auto_20190310_0132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='no_of_local_governments',
            field=models.PositiveIntegerField(),
        ),
    ]
