# Generated by Django 2.1.7 on 2019-03-09 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('states', '0003_auto_20190310_0142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='landmarks',
            field=models.CharField(max_length=500),
        ),
    ]
