# Generated by Django 2.1.7 on 2019-03-09 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('states', '0004_auto_20190310_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='landmarks',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='state',
            name='no_of_local_governments',
            field=models.PositiveIntegerField(default='N/A'),
        ),
    ]
