AWS_ACCESS_KEY_ID = 'AKIAJFMSCSXRRQNKSKLA'
AWS_SECRET_ACCESS_KEY = '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'
AWS_STORAGE_BUCKET_NAME = 'dev-ng-api'
AWS_S3_CUSTOM_DOMAIN = '%s.s3.amazonaws.com' % AWS_STORAGE_BUCKET_NAME
SECRET_KEY = 'e!67s5^d%kew*hrhutettk%=z%irzjdlv@%b$78)de91@w%@!f'

