# Generated by Django 2.1.7 on 2019-03-09 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FederalMinistry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=400)),
                ('short_name', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('established', models.DateTimeField()),
                ('current_minister', models.CharField(max_length=500)),
                ('permanent_secretary', models.CharField(default='N\\A', max_length=500)),
                ('headquarters', models.CharField(default='Abuja', max_length=100)),
                ('twitter', models.URLField(blank=True, default='N/A', null=True)),
                ('website', models.URLField(blank=True, default='N/A', null=True)),
            ],
        ),
    ]
