# Generated by Django 2.1.7 on 2019-03-09 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federal_ministries', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='federalministry',
            options={'verbose_name_plural': 'Federal Ministries'},
        ),
        migrations.AlterField(
            model_name='federalministry',
            name='established',
            field=models.PositiveIntegerField(),
        ),
    ]
