# Generated by Django 2.1.7 on 2019-03-09 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('federal_ministries', '0002_auto_20190310_0129'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='federalministry',
            options={'verbose_name': 'Federal Ministries', 'verbose_name_plural': 'Federal Ministries'},
        ),
    ]
