# Generated by Django 2.1.7 on 2019-03-09 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('federal_ministries', '0003_auto_20190310_0131'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='federalministry',
            options={'verbose_name_plural': 'Federal Ministries'},
        ),
    ]
