# Generated by Django 2.1.7 on 2019-03-15 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('state', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('domestic', 'domestic'), ('international', 'international')], max_length=100)),
                ('established', models.PositiveIntegerField()),
                ('website', models.URLField(blank=True, default='N/A', null=True)),
            ],
        ),
    ]
