# Generated by Django 2.1.7 on 2019-03-07 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=300)),
                ('nick_name', models.CharField(max_length=50)),
                ('campuses', models.CharField(blank=True, max_length=200, null=True)),
                ('established', models.PositiveIntegerField()),
                ('location', models.CharField(max_length=500)),
                ('type', models.CharField(max_length=20)),
                ('chancellor', models.CharField(blank=True, max_length=400, null=True)),
                ('vice_chancellor', models.CharField(max_length=400)),
                ('motto', models.CharField(blank=True, max_length=300, null=True)),
                ('logo', models.ImageField(upload_to='university_logos')),
            ],
            options={
                'ordering': ('full_name',),
            },
        ),
    ]
