# Generated by Django 2.1.7 on 2019-03-15 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=300)),
                ('nick_name', models.CharField(max_length=50)),
                ('campuses', models.CharField(blank=True, default='N/A', max_length=200, null=True)),
                ('established', models.PositiveIntegerField()),
                ('town', models.CharField(default='N/A', max_length=100)),
                ('state', models.CharField(default='N/A', max_length=50)),
                ('type', models.CharField(choices=[('private', 'private'), ('state', 'state'), ('federal', 'federal')], default='', max_length=20)),
                ('chancellor', models.CharField(blank=True, default='N/A', max_length=400, null=True)),
                ('vice_chancellor', models.CharField(max_length=400)),
                ('motto', models.CharField(blank=True, default='N/A', max_length=300, null=True)),
                ('website', models.URLField(default='N/A')),
                ('logo', models.ImageField(blank=True, default='N/A', null=True, upload_to='university_logos')),
            ],
            options={
                'verbose_name_plural': 'Universities',
                'ordering': ('full_name',),
            },
        ),
    ]
