# Generated by Django 2.1.7 on 2019-03-07 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='university',
            options={'ordering': ('full_name',), 'verbose_name_plural': 'Universities'},
        ),
        migrations.AlterField(
            model_name='university',
            name='type',
            field=models.CharField(choices=[('Private', 'Private'), ('State', 'State-owned'), ('Federal', 'Federal-government-owned')], default='', max_length=20),
        ),
    ]
