# Generated by Django 2.1.7 on 2019-03-07 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0002_auto_20190307_0303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='type',
            field=models.CharField(choices=[('Private', 'Private'), ('State', 'State'), ('Federal', 'Federal')], default='', max_length=20),
        ),
    ]
