# Generated by Django 2.1.7 on 2019-03-08 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0004_auto_20190308_0236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='campuses',
            field=models.CharField(blank=True, default='N/A', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='chancellor',
            field=models.CharField(blank=True, default='N/A', max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='logo',
            field=models.ImageField(blank=True, default='N/A', null=True, upload_to='university_logos'),
        ),
        migrations.AlterField(
            model_name='university',
            name='motto',
            field=models.CharField(blank=True, default='N/A', max_length=300, null=True),
        ),
    ]
