# Generated by Django 2.1.7 on 2019-03-09 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0005_auto_20190308_0245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='university',
            name='location',
        ),
        migrations.AddField(
            model_name='university',
            name='state',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='university',
            name='town',
            field=models.CharField(default='N/A', max_length=100),
        ),
    ]
