# Generated by Django 2.1.7 on 2019-03-09 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0006_auto_20190309_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='website',
            field=models.URLField(default='N/A'),
        ),
    ]
